name: JAMForgeProfileCreator
options:
  bundleIdPrefix: com.jamforge
  deploymentTarget:
    macOS: 13.0
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  createIntermediateGroups: true

settings:
  base:
    SWIFT_VERSION: 5.9
    MACOSX_DEPLOYMENT_TARGET: 13.0
    DEVELOPMENT_TEAM: # Your team ID here
    CODE_SIGN_STYLE: Automatic
    ENABLE_HARDENED_RUNTIME: YES

targets:
  JAMForgeProfileCreator:
    type: application
    platform: macOS
    sources:
      - path: JAMForgeProfileCreator
        excludes:
          - "Documentation/*"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.jamforge.profilecreator
        INFOPLIST_FILE: JAMForgeProfileCreator/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_NSHumanReadableCopyright: "Copyright © 2025 JAMForge. All rights reserved."
        INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.utilities
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
    dependencies:
      - package: XMLCoder
      - package: KeychainAccess
      - package: swift-crypto
      - package: swift-log
    postBuildScripts:
      - name: SwiftLint
        script: |
          if which swiftlint > /dev/null; then
            swiftlint
          else
            echo "warning: SwiftLint not installed"
          fi

  JAMForgeProfileCreatorTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - Tests/JAMForgeProfileCreatorTests
    dependencies:
      - target: JAMForgeProfileCreator

  JAMForgeProfileCreatorUITests:
    type: bundle.ui-testing
    platform: macOS
    sources:
      - Tests/JAMForgeProfileCreatorUITests
    dependencies:
      - target: JAMForgeProfileCreator

packages:
  XMLCoder:
    url: https://github.com/CoreOffice/XMLCoder.git
    from: 0.17.1
  KeychainAccess:
    url: https://github.com/kishikawakatsumi/KeychainAccess.git
    from: 4.2.2
  swift-crypto:
    url: https://github.com/apple/swift-crypto.git
    from: 3.0.0
  swift-log:
    url: https://github.com/apple/swift-log.git
    from: 1.5.3
